In [59]:
import requests
import json
import pandas as pd

term = "drug AND (\"toxicity prediction\" OR \"predicting toxicity\") AND \"graph neural network\""
sort = "RELEVANT_DESC"
limit = "50"
searchDateFrom = "2015-01-01T00:00:00.000Z"
skip = 0
categoryIds = "605c72ef153207001f6470ce"

allhits = pd.DataFrame([], columns=["title", "abstract", "published date", "doi"])

while True:
    url = "https://chemrxiv.org/engage/chemrxiv/public-api/v1/items?term=" + term + "&sort=" + sort + "&limit=" + limit + "&searchDateFrom=" + searchDateFrom +"&skip=" + f"{skip}" + "&categoryIds=" + categoryIds
    
    response = requests.get(url)
    
    if response.status_code != 200:
        print("ERROR!")
        break
    else:
        data = response.json()
        if len(data["itemHits"]) == 0:
            print("FINISHED!")
            break
        else:
            for i, hit in enumerate(data["itemHits"]):
                title = hit["item"]["title"]
                abstract = hit["item"]["abstract"]
                date = hit["item"]["publishedDate"]
                doi = hit["item"]["doi"]
                allhits = pd.concat([allhits, pd.DataFrame(data=[[title, abstract, date, doi]], columns=["title", "abstract", "published date", "doi"])], axis=0)
            skip += 50
            print(f"No.{skip} finished")

No.50 finished
No.100 finished
No.150 finished
No.200 finished
No.250 finished
No.300 finished
No.350 finished
No.400 finished
No.450 finished
No.500 finished
No.550 finished
No.600 finished
No.650 finished
FINISHED!

TypeError: 'tuple' object is not callable

In [62]:
allhits.reset_index(inplace=True, drop=True)
allhits.to_csv("/workspace/liz/SRToxPred/survey_list/240701_ChemRxiv_hits.csv")

In [57]:
term = "drug AND (\"toxicity prediction\" OR \"predicting toxicity\") AND \"graph neural network\""
sort = "RELEVANT_DESC"
limit = "50"
searchDateFrom = "2015-01-01T00:00:00.000Z"
skip = "0"
categoryIds = "605c72ef153207001f6470ce"

url = "https://chemrxiv.org/engage/chemrxiv/public-api/v1/items?term=" + term + "&sort=" + sort + "&limit=" + limit + "&searchDateFrom=" + searchDateFrom +"&skip=" + skip + "&categoryIds=" + categoryIds
response = requests.get(url)
data = response.json()

data["itemHits"][0]["item"]["title"]

'Equivariant Graph Neural Networks for Toxicity Prediction'

In [40]:
import pprint
pprint.pprint(data)
print(len(data["itemHits"]))

{'itemHits': [], 'totalCount': 649}
0

In [52]:
results = pd.DataFrame([], columns=["title", "abstract", "published date", "doi"])
display(results)
pd.concat([results, pd.DataFrame(data=[[1, 2, 3, 4]], columns=["title", "abstract", "published date", "doi"])], axis=0)

Empty DataFrame
Columns: [title, abstract, published date, doi]
Index: []

  title abstract published date doi
0     1        2              3   4

In [7]:
import json
with open("./test.json", "w") as f:
    json.dump(data, f)

In [13]:
with open("/workspace/liz/SRToxPred/notebook/test.json", "r") as f:
    d = json.load(f)

pprint.pprint(d)

{'itemHits': [{'item': {'abstract': 'Metal ions are irreplaceable in many '
                                    'areas of chemistry, including '
                                    '(bio)catalysis, self-assembly and charge '
                                    'transfer processes.  Yet, modelling their '
                                    'structural and dynamic properties in '
                                    'diverse chemical environments remains '
                                    'challenging for both force fields and ab '
                                    'initio methods. Here, we introduce a '
                                    'strategy to train machine learning '
                                    'potentials (MLPs) using MACE, an '
                                    'equivariant message-passing neural '
                                    'network, for metal-ligand complexes in '
                                    'explicit solvents. We explore the '
                                    'structure and ligand exchange dynamics of '
                                    'Mg2+ in water and Pd2+ in acetonitrile as '
                                    'two illustrative model systems. The '
                                    'trained potentials accurately reproduce '
                                    'equilibrium structures of the complexes '
                                    'in solution, including different '
                                    'coordination numbers and geometries. '
                                    'Furthermore, the MLPs can model '
                                    'structural changes between metal ions and '
                                    'ligands in the first coordination shell, '
                                    'and reproduce the free energy barriers '
                                    'for the corresponding ligand exchange. '
                                    'The strategy presented here provides a '
                                    'computationally efficient approach to '
                                    'model metal ions in solution, paving the '
                                    'way for modelling larger and more diverse '
                                    'metal complexes relevant to biomolecules '
                                    'and supramolecular assemblies. ',
                        'approvedDate': '2024-06-28T10:52:31.735Z',
                        'asset': {'fileName': 'manuscript.pdf',
                                  'fileSizeBytes': 5962617,
                                  'id': '667d7f26e97c028476ac63d9',
                                  'largeThumbnail': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667d74bc01103d79c546ba89/largeThumb/modelling-ligand-exchange-in-metal-complexes-with-machine-learning-potentials.jpg'},
                                  'mediumThumbnail': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667d74bc01103d79c546ba89/mediumThumb/modelling-ligand-exchange-in-metal-complexes-with-machine-learning-potentials.jpg'},
                                  'mimeType': 'application/pdf',
                                  'original': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667d74bc01103d79c546ba89/original/modelling-ligand-exchange-in-metal-complexes-with-machine-learning-potentials.pdf'},
                                  'smallThumbnail': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667d74bc01103d79c546ba89/smallThumb/modelling-ligand-exchange-in-metal-complexes-with-machine-learning-potentials.jpg'}},
                        'authors': [{'firstName': 'Veronika',
                                     'institutions': [{'country': '',
                                                       'name': 'Chemistry '
                                                               'Research '
                                                               'Laboratory, '
                                                               'University of '
                                                               'Oxford, '
                                                               'Oxford, OX1 '
                                                               '3TA, UK',
                                                       'rorId': ''}],
                                     'lastName': 'Juraskova',
                                     'orcid': '0000-0002-6293-5616',
                                     'title': 'Dr'},
                                    {'firstName': 'Gers',
                                     'institutions': [{'country': '',
                                                       'name': 'Center for '
                                                               'Theoretical '
                                                               'Chemistry, '
                                                               'Ruhr '
                                                               'University '
                                                               'Bochum, '
                                                               'D-44780 '
                                                               'Bochum, '
                                                               'Germany',
                                                       'rorId': ''}],
                                     'lastName': 'Tusha',
                                     'orcid': '0000-0002-2869-461X',
                                     'title': None},
                                    {'firstName': 'Hanwen',
                                     'institutions': [{'country': '',
                                                       'name': 'Chemistry '
                                                               'Research '
                                                               'Laboratory, '
                                                               'University of '
                                                               'Oxford, '
                                                               'Oxford, OX1 '
                                                               '3TA, UK',
                                                       'rorId': ''}],
                                     'lastName': 'Zhang',
                                     'orcid': None,
                                     'title': None},
                                    {'firstName': 'Lars',
                                     'institutions': [{'country': '',
                                                       'name': 'Center for '
                                                               'Theoretical '
                                                               'Chemistry, '
                                                               'Ruhr '
                                                               'University '
                                                               'Bochum, '
                                                               'D-44780 '
                                                               'Bochum, '
                                                               'Germany',
                                                       'rorId': ''}],
                                     'lastName': 'Schäfer',
                                     'orcid': None,
                                     'title': 'Prof'},
                                    {'firstName': 'Fernanda',
                                     'institutions': [{'country': '',
                                                       'name': 'Chemistry '
                                                               'Research '
                                                               'Laboratory, '
                                                               'University of '
                                                               'Oxford, '
                                                               'Oxford, OX1 '
                                                               '3TA, UK',
                                                       'rorId': ''}],
                                     'lastName': 'Duarte',
                                     'orcid': None,
                                     'title': 'Prof'}],
                        'categories': [{'description': 'Research on '
                                                       'Theoretical and '
                                                       'Computational '
                                                       'Chemistry',
                                        'id': '605c72ef153207001f6470ce',
                                        'name': 'Theoretical and Computational '
                                                'Chemistry'}],
                        'commentsCount': 0,
                        'competingInterestsDeclaration': None,
                        'contentType': {'id': '5ce663395846762193c9c430',
                                        'name': 'Working Paper'},
                        'doi': '10.26434/chemrxiv-2024-6lvk7',
                        'event': None,
                        'funders': [{'funderId': '10.13039/501100001659',
                                     'grantNumber': '331085229',
                                     'name': 'Deutsche Forschungsgemeinschaft',
                                     'title': None,
                                     'url': None},
                                    {'funderId': '',
                                     'grantNumber': '210737',
                                     'name': 'Swiss National Science '
                                             'Foundation',
                                     'title': None,
                                     'url': None},
                                    {'funderId': '10.13039/501100000266',
                                     'grantNumber': 'EP/L015722/1',
                                     'name': 'Engineering and Physical '
                                             'Sciences Research Council',
                                     'title': None,
                                     'url': None}],
                        'gainedEthicsApproval': 'NOT_RELEVANT',
                        'hasCompetingInterests': False,
                        'id': '667d74bc01103d79c546ba89',
                        'isLatestVersion': True,
                        'keywords': ['machine learning potentials',
                                     'active learning',
                                     'chemical reactions',
                                     'explicit solvent',
                                     'metal ion',
                                     'ligand exchange'],
                        'latestComments': [],
                        'legacyId': None,
                        'license': {'description': 'This license will allow '
                                                   'Site users to copy and '
                                                   'redistribute the Content '
                                                   'in any medium or format '
                                                   'and remix, transform and '
                                                   'build upon the Content for '
                                                   'any purpose, even '
                                                   'commercially. There is a '
                                                   'requirement to attribute '
                                                   'the Author upon reuse of '
                                                   'the Content.',
                                    'id': '5cc9d9bf7d4e0000ac04ef23',
                                    'name': 'CC BY 4.0',
                                    'url': 'https://creativecommons.org/licenses/by/4.0/'},
                        'metrics': [{'description': 'Abstract Views',
                                     'value': 71},
                                    {'description': 'Citations', 'value': 0},
                                    {'description': 'Content Downloads',
                                     'value': 33}],
                        'origin': 'CHEMRXIV',
                        'publishedDate': '2024-06-28T10:52:49.356Z',
                        'status': 'PUBLISHED',
                        'statusDate': '2024-06-28T10:52:49.356Z',
                        'subject': {'description': 'Discover early research '
                                                   'outputs such as working '
                                                   'papers, posters and '
                                                   'presentations in '
                                                   'Chemistry.',
                                    'id': '5e68cb1bd1f19d49ce3ac739',
                                    'name': 'Chemistry'},
                        'submittedDate': '2024-06-27T16:03:39.958Z',
                        'suppItems': [{'asset': {'fileName': 'supp_info.pdf',
                                                 'fileSizeBytes': 7784193,
                                                 'id': '667d8ce1e97c028476b027b4',
                                                 'largeThumbnail': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667d8226c9c6a5c07a9b7357/largeThumb/supporting-information.jpg'},
                                                 'mediumThumbnail': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667d8226c9c6a5c07a9b7357/mediumThumb/supporting-information.jpg'},
                                                 'mimeType': 'application/pdf',
                                                 'original': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667d8226c9c6a5c07a9b7357/original/supporting-information.pdf'},
                                                 'smallThumbnail': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667d8226c9c6a5c07a9b7357/smallThumb/supporting-information.jpg'}},
                                       'description': 'Supporting information '
                                                      'describing '
                                                      'hyperparameters used,  '
                                                      'details on the '
                                                      'validation of the '
                                                      'potentials,  details on '
                                                      'the properties of the '
                                                      'systems.',
                                       'id': '667d8226c9c6a5c07a9b7357',
                                       'title': 'Supporting Information '}],
                        'termsAcceptance': True,
                        'title': 'Modelling ligand exchange in metal complexes '
                                 'with machine learning potentials',
                        'version': '1',
                        'versionNote': '',
                        'versionRefs': [{'itemId': '667d74bc01103d79c546ba89',
                                         'legacyId': None,
                                         'version': '1'}],
                        'vor': None,
                        'webLinks': []}},
              {'item': {'abstract': 'Machine learning (ML) is gaining momentum '
                                    'in chemistry for the prediction of '
                                    'various molecular properties, or for the '
                                    'generation of novel molecules with '
                                    'specific properties. However, these '
                                    'models can only be trained on relatively '
                                    'scarce, often low-quality data. Thus, '
                                    'memorization (rather than learn-ing) may '
                                    'result in poorly generalizable models. To '
                                    'address this issue, we aimed to revisit '
                                    'the way ML is practiced in chemistry. '
                                    'Using pKa prediction as an example, we '
                                    'present our strategy which involves '
                                    'imparting Chemistry knowledge to ML '
                                    'algorithms. We posit that teaching '
                                    'fundamental principles (e.g., '
                                    'electronegativity and inductive effect) '
                                    'to machines to predict properties (e.g., '
                                    'pKa), analogous to the way we teach '
                                    'students, will allow them to predict more '
                                    'advanced, yet related, properties. Thus, '
                                    'ML will leverage the chemists’ knowledge '
                                    'and qualitative principles to quantify '
                                    'and predict chemical properties.',
                        'approvedDate': '2024-06-28T08:12:43.436Z',
                        'asset': {'fileName': 'Moitessier - pKa predictor - '
                                              'ChemRXiv 20240627.pdf',
                                  'fileSizeBytes': 1101082,
                                  'id': '667dffeddde6de140639c7f0',
                                  'largeThumbnail': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667dffb55101a2ffa8bed079/largeThumb/leveraging-our-teacher-s-experience-to-improve-machine-learning-application-to-p-ka-prediction.jpg'},
                                  'mediumThumbnail': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667dffb55101a2ffa8bed079/mediumThumb/leveraging-our-teacher-s-experience-to-improve-machine-learning-application-to-p-ka-prediction.jpg'},
                                  'mimeType': 'application/pdf',
                                  'original': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667dffb55101a2ffa8bed079/original/leveraging-our-teacher-s-experience-to-improve-machine-learning-application-to-p-ka-prediction.pdf'},
                                  'smallThumbnail': {'url': 'https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/667dffb55101a2ffa8bed079/smallThumb/leveraging-our-teacher-s-experience-to-improve-machine-learning-application-to-p-ka-prediction.jpg'}},
                        'authors': [{'firstName': 'Jérôme',
                                     'institutions': [{'country': 'Canada',
                                                       'name': 'McGill '
                                                               'University',
                                                       'rorId': 'https://ror.org/01pxwe438'}],
                                     'lastName': 'Genzling',
                                     'orcid': '0009-0007-4728-1478',
                                     'title': 'Mr'},
                                    {'firstName': 'Ziling',
                                     'institutions': [{'country': 'Canada',
                                                       'name': 'McGill '
                                                               'University',

In [17]:
import arxiv
import pprint
import pandas as pd

client = arxiv.Client()

l = client.results(arxiv.Search(query='all:"toxicity prediction" AND cat:cs.AI'))
cnt = 0
for i in l:
    print(i)
    cnt += 1
    if cnt == 10:
        break

http://arxiv.org/abs/2309.12177v2
http://arxiv.org/abs/2102.10062v4
http://arxiv.org/abs/2009.12199v1
http://arxiv.org/abs/2202.09662v6
http://arxiv.org/abs/2005.00813v1
http://arxiv.org/abs/2301.08577v1
http://arxiv.org/abs/2205.08055v1
http://arxiv.org/abs/1706.06689v1

In [76]:
import urllib, urllib.request
url = 'http://export.arxiv.org/api/query?search_query=all:electron&start=0&max_results=1'
data = urllib.request.urlopen(url)
print(data)
print(data.read().decode("utf-8"))

<http.client.HTTPResponse object at 0x746fe146ae00>
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <link href="http://arxiv.org/api/query?search_query%3Dall%3Aelectron%26id_list%3D%26start%3D0%26max_results%3D1" rel="self" type="application/atom+xml"/>
  <title type="html">ArXiv Query: search_query=all:electron&amp;id_list=&amp;start=0&amp;max_results=1</title>
  <id>http://arxiv.org/api/cHxbiOdZaP56ODnBPIenZhzg5f8</id>
  <updated>2024-07-01T00:00:00-04:00</updated>
  <opensearch:totalResults xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/">211733</opensearch:totalResults>
  <opensearch:startIndex xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/">0</opensearch:startIndex>
  <opensearch:itemsPerPage xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/">1</opensearch:itemsPerPage>
  <entry>
    <id>http://arxiv.org/abs/cond-mat/0102536v1</id>
    <updated>2001-02-28T20:12:09Z</updated>
    <published>2001-02-28T20:12:09Z</published>
    <title>Impact of Electron-Electron Cusp on Configuration Interaction Energies</title>
    <summary>  The effect of the electron-electron cusp on the convergence of configuration
interaction (CI) wave functions is examined. By analogy with the
pseudopotential approach for electron-ion interactions, an effective
electron-electron interaction is developed which closely reproduces the
scattering of the Coulomb interaction but is smooth and finite at zero
electron-electron separation. The exact many-electron wave function for this
smooth effective interaction has no cusp at zero electron-electron separation.
We perform CI and quantum Monte Carlo calculations for He and Be atoms, both
with the Coulomb electron-electron interaction and with the smooth effective
electron-electron interaction. We find that convergence of the CI expansion of
the wave function for the smooth electron-electron interaction is not
significantly improved compared with that for the divergent Coulomb interaction
for energy differences on the order of 1 mHartree. This shows that, contrary to
popular belief, description of the electron-electron cusp is not a limiting
factor, to within chemical accuracy, for CI calculations.
</summary>
    <author>
      <name>David Prendergast</name>
      <arxiv:affiliation xmlns:arxiv="http://arxiv.org/schemas/atom">Department of Physics</arxiv:affiliation>
    </author>
    <author>
      <name>M. Nolan</name>
      <arxiv:affiliation xmlns:arxiv="http://arxiv.org/schemas/atom">NMRC, University College, Cork, Ireland</arxiv:affiliation>
    </author>
    <author>
      <name>Claudia Filippi</name>
      <arxiv:affiliation xmlns:arxiv="http://arxiv.org/schemas/atom">Department of Physics</arxiv:affiliation>
    </author>
    <author>
      <name>Stephen Fahy</name>
      <arxiv:affiliation xmlns:arxiv="http://arxiv.org/schemas/atom">Department of Physics</arxiv:affiliation>
    </author>
    <author>
      <name>J. C. Greer</name>
      <arxiv:affiliation xmlns:arxiv="http://arxiv.org/schemas/atom">NMRC, University College, Cork, Ireland</arxiv:affiliation>
    </author>
    <arxiv:doi xmlns:arxiv="http://arxiv.org/schemas/atom">10.1063/1.1383585</arxiv:doi>
    <link title="doi" href="http://dx.doi.org/10.1063/1.1383585" rel="related"/>
    <arxiv:comment xmlns:arxiv="http://arxiv.org/schemas/atom">11 pages, 6 figures, 3 tables, LaTeX209, submitted to The Journal of
  Chemical Physics</arxiv:comment>
    <arxiv:journal_ref xmlns:arxiv="http://arxiv.org/schemas/atom">J. Chem. Phys. 115, 1626 (2001)</arxiv:journal_ref>
    <link href="http://arxiv.org/abs/cond-mat/0102536v1" rel="alternate" type="text/html"/>
    <link title="pdf" href="http://arxiv.org/pdf/cond-mat/0102536v1" rel="related" type="application/pdf"/>
    <arxiv:primary_category xmlns:arxiv="http://arxiv.org/schemas/atom" term="cond-mat.str-el" scheme="http://arxiv.org/schemas/atom"/>
    <category term="cond-mat.str-el" scheme="http://arxiv.org/schemas/atom"/>
  </entry>
</feed>

In [9]:
import pandas as pd

chemrxiv = pd.read_csv("/workspace/liz/SRToxPred/survey_list/240701_ChemRxiv_hits.csv", index_col=0)
for i in range(len(chemrxiv)):
    if "\n" in chemrxiv.iloc[i, 0]:
        chemrxiv.iloc[i, 0] = chemrxiv.iloc[i, 0].replace("\n", " ")
    if "\n" in chemrxiv.iloc[i, 1]:
        chemrxiv.iloc[i, 1] = chemrxiv.iloc[i, 1].replace("\n", " ")

In [11]:
chemrxiv.to_csv("/workspace/liz/SRToxPred/survey_list/240701_ChemRxiv_hits.csv")

In [17]:
chemrxiv.iloc[20, 1]

'Since the structures of crystals/molecules are often non-Euclidean data in real space, graph neural networks (GNNs) are regarded as the most prospective approach for their capacity of representing materials by graph-based inputs and emerged as an efficient and powerful tool in accelerating the discovery of new materials. Here, we proposed a self-learning-input GNN framework, named SLI-GNN, to uniformly predict the properties for both crystals and molecules, in which, for the first time, we design a dynamic embedding layer to self-update the input features along with the iteration of the neural network and introduce the Infomax mechanism to maximize the average mutual information between the local features and the global features. It is found that our SLI-GNN can reach ideal prediction accuracy with less inputs and more MPNN layers. The model evaluation on the Materials Project Dataset and QM9 dataset verify that the overall performance of our GNN is comparable to that of other previously reported GNNs. Thus, our GNN framework presents excellent performance in material property prediction, thereby being promising for accelerating the discovery of new materials.\u2003'

In [93]:
import arxiv
import pprint
import pandas as pd
import pytz

client = arxiv.Client()
now = datetime.now(pytz.timezone("Asia/Tokyo"))
old = now - timedelta(1)
now = old.strftime("%Y%m%d") + "2359"
old = old.strftime("%Y%m%d") + "0000"
print(now, old)

l = client.results(arxiv.Search(query=f'%28cat:q-bio.BM OR cat:q-bio.GN OR cat:q-bio.NC OR cat:q-bio.MN%29 AND submittedDate:[{old} TO {now}]'))
for i in l:
    x = str(i)
    print(x)
    print(type(x))
print(cnt)

202407032359 202407030000
http://arxiv.org/abs/2407.02984v1
<class 'str'>
http://arxiv.org/abs/2407.03154v1
<class 'str'>
http://arxiv.org/abs/2407.03089v1
<class 'str'>
0

In [ ]:
l = client.results(arxiv.Search(query=f'all:drug AND all:toxicity AND %28all:"neural network" OR all:"deep learning"%29 AND submittedDate:[201501010000 TO {now}]'))

In [41]:
l = client.results(arxiv.Search(query=f'%28cat:q-bio.BM OR cat:q-bio.GN OR cat:q-bio.NC OR cat:q-bio.MN%29 AND submittedDate:[{old} TO {now}]'))

2024-07-03 15:45:21.045090

In [35]:
query=f'cat:cs.AI AND cat:cs.LG AND submittedDate:[{{{datetime.now().date() - timedelta(1)}}}]'

In [36]:
print(query)

cat:cs.AI AND cat:cs.LG AND submittedDate:[{2024-07-03}]

# Get Arxiv paper

In [4]:
import requests
import arxiv
from datetime import datetime, timedelta
import pytz
import numpy as np
import pandas as pd

In [9]:
client = arxiv.Client()
end = datetime.now(pytz.timezone("Asia/Tokyo"))
start = "201501010000"
end = end.strftime("%Y%m%d") + "0000"

res_list = []

res = client.results(arxiv.Search(query=f'%28%28drug OR chemical%29 AND toxicity AND %28%28neural network%29 OR %28deep learning%29%29 AND %28graph OR SMILES OR strings%29%29 AND submittedDate:[{start} TO {end}]'))
cnt = 0
for r in res:
    info = []
    info.append(r.title)
    info.append(r.summary)
    info.append(str(r))
    res_list.append(info)
    cnt += 1

res_df = pd.DataFrame(columns=["Title", "Abstract", "Link"], index=np.arange(len(res_list)))

if cnt == 0 and len(res_list) == 0:
    print("やり直せｋｓ")
else:
    print(f"とりあえずおｋ、件数は{len(res_list)}")
    for i in range(cnt):
        res_df.loc[i] = [res_list[i][0], res_list[i][1], res_list[i][2]]
    display(res_df.head())
    print(res_df.shape)
    res_df.to_csv("/workspace/liz/SRToxPred/survey_list/Arxiv_list_240818.csv")

とりあえずおｋ、件数は32

,Title,Abstract,Link
0,DeepCCI: End-to-end Deep Learning for Chemical...,Chemical-chemical interaction (CCI) plays a ke...,http://arxiv.org/abs/1704.08432v3
1,Accelerating Drug Safety Assessment using Bidi...,Computational methods are useful in accelerati...,http://arxiv.org/abs/2407.18919v1
2,Toxicity Detection in Drug Candidates using Si...,The need for analysis of toxicity in new drug ...,http://arxiv.org/abs/2101.10831v1
3,SMILES-Mamba: Chemical Mamba Foundation Models...,"In drug discovery, predicting the absorption, ...",http://arxiv.org/abs/2408.05696v1
4,Network-principled deep generative models for ...,Combination therapy has shown to improve thera...,http://arxiv.org/abs/2004.07782v2

(32, 3)